### ISSUE TITLE
詳細ページの投稿者ボックス内のバグ

### ISSUE THREAD

**Issue by yat8823jp** [inc2734/snow-monkey#1]
PCサイズで記事一覧ボタンの下線が切れてしまうようです。
ソースを見て触ってみたけど、どうしても修正箇所を特定できなかったのでissueにあげました。

![2017-10-06 21 57 42](https://user-images.githubusercontent.com/1327196/31280793-7bf68a72-aae8-11e7-959d-8c9868d08161.png)

**Comment by inc2734** [comment]
実はこれ僕も把握済みなのです。僕も原因がわからずとりあえずそのままにしています。ソーシャルの URL を設定したらちゃんとでるんですよね。落ち着いたらまた改めて調査します。issue 立てて頂いてありがとうございます！

**Comment by yat8823jp** [comment]
ソース _wp-profile-box.scss にある
  &__buttons {
    @include _margin(.5, 0, 0);
  }
っていうのは見つけたんですけど、デベロッパーツールだと .9 になってて、どういう仕組みかわからずで。
@include _margin
これってどこに定義されてるのでしょう？

**Comment by understandard** [comment]
下線が切れるのは
.wp-profile-box__body に指定してある overflow: hidden; ですね。
float + overflow ではなく、display: table-cell 等で実装するか、
.wp-profile-box__body に padding-bottom: 1px; のように回避するか
等の方法がありますね。

**Comment by inc2734** [comment]
@yat8823jp 
> これってどこに定義されてるのでしょう？
結構深いところにあるのであれですが、リファレンスとコードは下記で見れます。
https://sass-basis.github.io/basis/
https://github.com/sass-basis/basis/

**Comment by inc2734** [comment]
@understandard ひょー！ありがとうございます！そうか padding 足すのた安全で簡単ですね。影響範囲を狭めたいので .wp-profile-box__buttons につけるようにしようと思います。

**Comment by yat8823jp** [comment]
あ、ソース修正してる間にコメントが。＾＾；
bodyに1px足してプルリク送ってしまいました。
破棄でもOKですので！

**Comment by understandard** [comment]
@inc2734
とりあえず直すという案だけで深く考えて無かったです。すみません。
ハックっぽくない方法で、
.wp-profile-box__archives-btn に vertical-align: bottom; を指定するほうがよいですね。
