### ISSUE TITLE
ランキングウィジェットで過去の記事が出てこない

### ISSUE THREAD

**Issue by mihoji** [inc2734/snow-monkey#10]
全部で100件以上の記事があるのですが、最新の20件目くらいまでは順番に出てくるけど、それ以降、同じ記事がくりかえし表示されたりして、昔の記事が出て来ないため、古い記事で人気があるものを選択することができません。
![fireshot capture 174 - _ - https___ishida-webkontor com_wordpress_wp-admin_widgets php](https://user-images.githubusercontent.com/12166608/31370951-5763ad50-adc9-11e7-8787-688d6edea89d.png)

**Comment by inc2734** [comment]
こちら、約50件ほどの記事が登録されている僕のローカル開発環境では再現できませんでした。@mihoji さんに発行いただいたアカウントでログインし試させて頂いたところ、ずっと下までスクロールさせると「ウェブログ再開しました。」「About me」というところまで表示されました。同じサイトで発生するときとしないときがあるというのは不思議ですが、もしかしたら WordPress のクエリにフックするようなプラグインが何かあるのかもしれません（まだ深くおえてはいませんが…

ウィジェットの方も `get_posts()` で記事取得を行っているので、`WP_Query` で取得するように変更をいれたいと思います（多分そちらのほうが外からの影響が少ない気がする

**Comment by mihoji** [comment]
ほんとですね、いま、ためしたらいけました！
このテーマをインストールしたときからうまくいかず、しばらく時間をおいて何回か試してみて、過去記事に辿り着かなかったのでここに書いたのですが、いまは大丈夫です。不思議。
