### ISSUE TITLE
`Helper::load_files()` は動的なのでOPcacheやNFSと相性が悪い

### ISSUE THREAD

**Issue by harai** [inc2734/snow-monkey#1043]
Snow Monkeyでは [`Helper::load_files()`](https://github.com/inc2734/snow-monkey/blob/220438614d0eeac17565c5d659977f3fe0a4dadd/Framework/Helper.php#L48) を使って多くのコードが読み込まれていますが、この処理は動的なので

* OPcacheを有効化していてもディレクトリをスキャンしなければならず
* NFSのようなファイルアクセス時の遅延の大きい構成ではレスポンス速度が悪化する

という問題があります。また、特にAWSのEFSを用いた場合、リクエストごとに多量のメタデータのI/Oが発生しコストが増大します。

ロードするファイルのリストをビルド時に生成することで、これらの問題を解消することはできないでしょうか？

**Comment by inc2734** [comment]
なるほどです。要は

```
return [
  'app/setup/assets.php`,
  'app/setup/basis.php`,
  'app/setup/breadcrumbs.php`,
  ...
];
```

というファイルを生成しておいて、それを

```
$setup_files = include_once( '生成したファイル' );
foreach ( $setup_files as $file ) {
  Helper::get_template_part( $file );
}
```

のようにできると良いということですかね？

**Comment by harai** [comment]
@inc2734 はい、そうです！

**Comment by inc2734** [comment]
なるほど！OPcache もサーバーも詳しくないので一応確認でした。ファイルを生成するのはできそうな気がするのでちょっとやってみます！

**Comment by inc2734** [comment]
`npm run build` したときに、`assets/load-files-target` ディレクトリ内に読み込み対象のファイルを列挙した json ファイルを生成し、実際の読み込み時に json ファイルが存在したらそこに書いてあるファイルを読み込むようにしてみました。これで改善がみられるでしょうか？

**Comment by harai** [comment]
@inc2734 今確認できないのですが、

そのような実装の場合、OPcacheを用いていてもJSONファイルは読み込まなければいけません。しかし、ディレクトリをスキャンする必要はなくなるのでディスクアクセスの回数や転送量は大きく減り、レスポンス速度も改善すると思います。

理想はすべてPHPだけで完結させることですが、互換性などの問題でそれが困難なのであれば、十分によい解決方法に思えます。

ありがとうございます。後ほど試してみます！

**Comment by inc2734** [comment]
そうか！なんとなく json にしてしまったので、PHP に修正します！

**Comment by inc2734** [comment]
@harai こちらどうでしたでしょうか？ 問題なさそうならリリースしたいと思います！

**Comment by harai** [comment]
```bash
npm run-script build
npm run-script zip
```

でビルドしましたが、 771ee384588d147d4d020cad2e0bcb0b2951485d (14.0.2) では何の問題もなく動作したものの、 9109efa では次のようなエラーログが出力され、また画面表示も大きく崩れました。

```
Notice: /var/www/html/wp-content/themes/snow-monkey/app/customizer/design/sections/post/controls/related-posts が見つかりません。削除または移動された可能性があります。 in /var/web/wp/wp-content/themes/snow-monkey/vendor/inc2734/wp-view-controller/src/setup/debug-template-overwrite.php on line 40
PHP Notice:  /var/www/html/wp-content/themes/snow-monkey/app/customizer/design/sections/header/controls/hamburger-btn-position が見つかりません。削除または移動された可能性があります。 in /var/web/wp/wp-content/themes/snow-monkey/vendor/inc2734/wp-view-controller/src/setup/debug-template-overwrite.php on line 40
Notice: /var/www/html/wp-content/themes/snow-monkey/app/customizer/design/sections/header/controls/hamburger-btn-position が見つかりません。削除または移動された可能性があります。 in /var/web/wp/wp-content/themes/snow-monkey/vendor/inc2734/wp-view-controller/src/setup/debug-template-overwrite.php on line 40
PHP Notice:  /var/www/html/wp-content/themes/snow-monkey/app/customizer/design/sections/header/controls/header-text-color が見つかりません。削除または移動された可能性があります。 in /var/web/wp/wp-content/themes/snow-monkey/vendor/inc2734/wp-view-controller/src/setup/debug-template-overwrite.php on line 40
```
（一部抜粋）

```bash
wp cache flush
```

をしてみましたが変わりませんでした。

私は `/var/web/wp` 下にWordPressを設置しています。 `/var/www/html` という決め打ちされた値に問題がありそうなのですが、この文字列はテストでのみ用いられているようで、どこで紛れ込んだのかは分かりませんでした。 @inc2734

**Comment by inc2734** [comment]
あーそうか、なるほど！wp-env 内で生成してるからでした。うっかりしてました、すみません。修正入れます！

**Comment by inc2734** [comment]
@harai wp-env のパスが決め打ちで入ってしまっていたので `get_template_directory()` を使うように変更しました！

**Comment by harai** [comment]
ありがとうございます。動作確認しました。　@inc2734 

AWS EFSを使ったほぼ空っぽの環境で、以前と比べてEFSとのデータの通信量が14%ほど減りました。まだ高い水準ですが、大きな改善であることは間違いありません。ありがとうございます。

引き続き調査を続け、改善できる点があればissue作成していきたいです。

**Comment by inc2734** [comment]
確認ありがとうございます！！それでも14%ですか…。あとはなんでしょうね、いちいち `file_exists()` で確認しているからとか、下記のようなところでもディレクトリをスキャンしてるから、とかですかね…。
https://github.com/inc2734/wp-view-controller/blob/5dcf1b0c50b81e86462576ea2dc7ae90127099a3/src/App/Contract/Template_Tag.php#L395-L396

> 引き続き調査を続け、改善できる点があればissue作成していきたいです。

すごくすごく助かります。なにかあったら気軽に issue 立ててください！

**Comment by harai** [comment]
`inc2734_wp_view_controller_debug` のフィルターを追加して、 `false` を返すようにしたらEFSとの転送量が20%になりました！ （なぜか `snow_monkey_debug` のフィルターを追加しても動作しませんでした）

**Comment by inc2734** [comment]
そこ！！全く予想外な部分でしたが、

```
apply_filters( 'inc2734_wp_view_controller_debug', WP_DEBUG )
```

にしましょうか。これなら開発中は有効で公開サイト上では無効になると思うので。

> なぜか snow_monkey_debug のフィルターを追加しても動作しませんでした

んーなんでしょうね。ちょっとみてみます。

**Comment by inc2734** [comment]
434edd3f86c7e0a246bad6c8629cac776bb24ad9

**Comment by harai** [comment]
テーマ内のPHPファイルを引数にして次のコードが繰り返し呼ばれていました。
これは普通のファイルとして開く処理なので、OPcacheは役に立たず、EFSとの通信がたくさん発生する原因になっていました。

https://github.com/inc2734/wp-view-controller/blob/5dcf1b0c50b81e86462576ea2dc7ae90127099a3/src/Helper.php#L24-L40

**Comment by inc2734** [comment]
```
apply_filters( 'inc2734_wp_view_controller_debug', WP_DEBUG )
```

となるように変更をいれました。また、`snow_monkey_debug` がちゃんと効くように修正しました。

**Comment by megane9988** [comment]
@inc2734  @harai 
素敵な修正！ありがとうございます。
二人の技術力の高さに惚れ惚れです！ 💯
