### ISSUE TITLE
特定のアクセントカラーを指定すると、ソース上のカラーコードが一部おかしくなる

### ISSUE THREAD

**Issue by rokuzeudon** [inc2734/snow-monkey#106]
例）
#0c0c0c →
.c-btn:hover,.c-btn:active,.c-btn:focus { background-color: #ffffffffffffffffffffffffffffffffffffffffffffffff }

#000000 →
.c-btn:hover,.c-btn:active,.c-btn:focus { background-color: #fffffffffffffff3fffffffffffffff3fffffffffffffff3 }

![2018-02-06 10 47 59](https://user-images.githubusercontent.com/14285777/35838160-4d56a65c-0b2d-11e8-9b01-fe8fd5c8c12f.jpg)

**Comment by inc2734** [comment]
む！ こちら、バージョンいくつをお使いでしょう？
現象は違いますが、同じ色調整するメソッドにバグがあって、v0.9.8 だったか v0.9.9 だかで修正をいれています。
https://github.com/inc2734/snow-monkey/issues/87

もしそれより古いバージョンをお使いでしたら、アップデートされてみてください。もし最新版をお使いでしたら…検証します…！

**Comment by inc2734** [comment]
あ、最新版でバグってますね、検証します(TT

**Comment by rokuzeudon** [comment]
ご確認ありがとうございます、お願いします！🙏

**Comment by rokuzeudon** [comment]
あ、ちなみに最新バージョンです！

**Comment by inc2734** [comment]
検証したところ、色を暗くするメソッドでの計算が #000 を超えたらバグるみたいでした。#000 を超えて黒くなるときは全部 #000 とするように修正して、v1.0.2 リリースします！（続々見つかるバグ…w）
