### ISSUE TITLE
ヘッダーレイアウト１行、かつアイキャッチ画像非表示の時にパンくずがクリックできない

### ISSUE THREAD

**Issue by rokuzeudon** [inc2734/snow-monkey#108]
表題の条件下だと、ヘッダーの要素が被ってしまいクリックできなくなっているようです。
（他のヘッダーレイアウトは問題ありませんでした！限定的なシチュエーションですが…）

![2018-02-06 13 38 05](https://user-images.githubusercontent.com/14285777/35842124-a14c5cf0-0b43-11e8-87b5-57bced0edf8c.jpg)

![2018-02-06 13 38 30](https://user-images.githubusercontent.com/14285777/35842131-a6a9bd5a-0b43-11e8-9657-7e5b12b90e2c.jpg)

**Comment by inc2734** [comment]
ありがとうございます！！！
