### ISSUE TITLE
WPAW:ショーケースウィジットにリンクを追加するとサムネイルが非常に小さくなる

### ISSUE THREAD

**Issue by munyagu** [inc2734/snow-monkey#11]
リンクを追加していない状態だと見えるサイズですが、少し長いリンクテキストが追加されると、サムネイルが非常に小さくなってしまいます。

![showcase_thumbnail](https://user-images.githubusercontent.com/19759754/31371658-16b06aa6-adcd-11e7-9cbd-52107f1e2c4d.jpg)

**Comment by inc2734** [comment]
ご報告ありがとうございます。縦並びにするブレイクポイントをずらすか、画像の min-width を定義するかで対応しようと思います。
