### ISSUE TITLE
ある条件下でウィジェット「PR ボックス」の項目が追加できなくなる

### ISSUE THREAD

**Issue by rokuzeudon** [inc2734/snow-monkey#116]
「PRボックス」ウィジェットで、「項目を追加」ボタンをクリックしても追加されず編集ができなくなる現象がありました。

**タイトル・リード文のみ入力した状態（項目の内容は空）で「適用」した**場合に発生するようです。

「項目」に何か入れてから適用すれば問題なく動きます。

SNOW MONKEY最新バージョン、Firefox・Chromeにて再現確認しました。

![2018-02-11 20 06 41](https://user-images.githubusercontent.com/14285777/36072724-de75d08e-0f67-11e8-9cd9-91cd17a8c66b.jpg)

**Comment by inc2734** [comment]
ご報告ありがとうございます、確認します！
