### ISSUE TITLE
フロントページの設定を固定ページにしても最新の投稿のまま

### ISSUE THREAD

**Issue by mekemoke** [inc2734/snow-monkey#12]
固定ページを選択すると「最新の投稿」というタイトルは表示されますが、固定ページの内容は表示されません。
（ブログやメディアサイト用のテーマということですので、仕様でしょうか…？）

**Comment by mekemoke** [comment]
（MAMP環境です）
子テーマを使わずに、該当の固定ページで「1カラム」を選択したところ、表示できました。
子テーマにしたところ、該当の固定ページのテンプレートを見ると「One Column」になっていました。
「1カラム」を選択したところ、
```
Warning: include(page-templates/one-column.php): failed to open stream: No such file or directory in /Applications/MAMP/htdocs/******/wordpress/wp-includes/template-loader.php on line 74

Warning: include(): Failed opening 'page-templates/one-column.php' for inclusion (include_path='.:/Applications/MAMP/bin/php/php7.1.6/lib/php') in /Applications/MAMP/htdocs/******/wordpress/wp-includes/template-loader.php on line 74
```
というエラーが表示されてしまいました。
そこで、「One Column」を選び直したところ、正常に表示されました。

ひとまず表示はされましたが、ご報告まで。

**Comment by inc2734** [comment]
> 固定ページを選択すると「最新の投稿」というタイトルは表示されますが、固定ページの内容は表示されません。

つくる過程で固定ページの内容を表示するかは悩んだのですが、今のところ「内容は表示されない」というのが仕様です。ちなみに、固定フロントページは下記のテンプレートで表示されます。
https://github.com/inc2734/snow-monkey/blob/master/resources/templates/view/front-page.php
非固定フロントページだとウィジェットエリアと pickup スライダーがナシになります。

> というエラーが表示されてしまいました。

これはバグですね…。ご報告ありがとうございます。検証してみます。
