### ISSUE TITLE
フォントサイズ大＋ 28pxがモバイルで36pxになる

### ISSUE THREAD

**Issue by miminari** [inc2734/snow-monkey#1201]
5.9対応ありがとうございます。

既に対応済みだったらすみません、ブロックエディタのプルダウンでフォントサイズ「大＋」(28px) を選択したブロック（class名`has-sm-xlarge-font-size`が付与される）で、モバイル画面サイズでフォントサイズが36pxになってしまうようです。フロントのみでエディタ側でモバイルプレビューを参照しても変化はありません。

該当箇所は
/wp-content/themes/snow-monkey/assets/css/app/app.css?ver=1642571605
の13142行でした
```
@media (max-width: 639px) {
  body {
    --wp--preset--font-size--sm-xlarge: calc(36px - (16px - var(--_base-font-size-px)));
```

28pxが正なのか、36pxが正なのか分からなくて、取り急ぎIssueだけですみません、一応ご報告でした。

検証環境：
Mac Chrome
WordPress 5.9 RC4
Snow Monkey バージョン: 16.0.0-beta2

![スクリーンショット 2022-01-25 11 27 48](https://user-images.githubusercontent.com/487207/150899834-9390afe9-fbe9-4ed6-bd54-0de14cb2f708.png)
![スクリーンショット 2022-01-25 11 28 04](https://user-images.githubusercontent.com/487207/150899846-3a65a3d9-aaf1-4ac9-b735-63e44a088894.png)

**Comment by inc2734** [comment]
確認します！

**Comment by inc2734** [comment]
`base-font-size` という `theme_mod` （基本文字サイズ）が変更されていないときは `Helper::get_font_sizes()` で正しく値が設定されずにこの不具合が発生するようでした。なので未設定のときは強制的に 16 で計算するようにしました。ご報告ありがとうございます！

**Comment by miminari** [comment]
対応ありがとうございます！
