### ISSUE TITLE
.translation/ と assets/ が gitignore されていない

### ISSUE THREAD

**Issue by waviaei** [inc2734/snow-monkey#1232]
> On branch develop
> Your branch is up to date with 'origin/develop'.
> 
> Untracked files:
>   (use "git add <file>..." to include in what will be committed)
> 	.node-version
> 	.translation/
> 	assets/

たぶん .gitignore の書き方で、先頭にスラッシュがあるため。

**Comment by inc2734** [comment]
clone した手元の PC のリポジトリでは ignore されていて、

<img width="299" alt="スクリーンショット 2022-04-21 15 37 06" src="https://user-images.githubusercontent.com/1094306/164389503-fc0e9d4e-b0da-4502-b158-734bf05a9908.png">

GitHub のリポジトリにも assets と .translation はアップされていないと思うのですが、そういうことではなくてですかね？

**Comment by waviaei** [comment]
僕の手元だと必ず `.translation` と `assetts` ディレクトリをgit に add しようとします。
 `git status` で確認すると👆のように、「トラッキングされていないディレクトリがありますよ」とでてきます。

**Comment by inc2734** [comment]
えっと、`On branch develop` となっているのがちょっと気になるのですが、master でもそうなりますかね？Snow Monkey の develop ブランチはかなり古い状態になっていて、ルートに `.transition` も `asseets` も無いのでもしかしたらその辺の影響もあるのかなと思いまして。もし master （head）でも再現するのであれば先頭のスラッシュを外すようにしたいと思います。

**Comment by waviaei** [comment]
その可能性ありますね。たぶんこのPRを書いたあとだったと思います、develop ブランチ古くてもう使っていないのかもなと気がついたのは。
明日確認してみます

https://github.com/inc2734/snow-monkey/blob/d12d1e0acaf06f5b74cb7b1b8ab4e05de25c8720/.github/CONTRIBUTING.md　はdevelopブランチになっているので修正必要ですね。
