### ISSUE TITLE
Customizer 用のファイルのロードを必要な時にのみ行うよう限定するパフォーマンス改善案

### ISSUE THREAD

**Issue by waviaei** [inc2734/snow-monkey#1239]
functions.php で3回 `Helper::load_files()`を使ってファイルが読み込まれているのですが、このうちの1つ、Customizer 用のファイルのロードをログイン時のみに限定できないでしょうか？
https://github.com/inc2734/snow-monkey/blob/5203b892ed4117ffc5085a2f1cd639a6767b4f14/functions.php#L115

試しにとあるプロジェクトのローカル環境で下記のようにして確認したところ……

```
if ( is_user_logged_in() ) {
	add_action(
		'init',
		function () {
		   ...
		},
		10000
	);
}
```

functions.php の  `Helper::load_files()` が実行している計255回の `inc2734\WP_View_Controller\Helper::get_template_part` が 計87回に減り、`Helper::get_template_part()` の合計処理時間も 621ms→385msへと約半分に減りました。
サイトにもよると思いますが、ファイル数は `/app/customizer` が一番多いようなので、ファイル数を減らす分だけファイル読み込みにおこなっている独自処理の実行時間をどのようなサイトでも減らすことができるかと思います。

以前相談した時にたしか「プレビュー時に必要なので `is_admin() `は使えない」ということでしたが、`is_user_logged_in()` ではどうでしょうか？

---

関連：
#1043

**Comment by inc2734** [comment]
多分、カスタマイザーのファイルを読み込まないとカスタマイザーで設定した値が正しく読み込まれないと思うので、できなさそうな気がします。

下記のフックを使って、読み込み対象が `app/customizer` のときだけ `$method` を `concat` にしてみるとどうでしょうか？
https://github.com/inc2734/snow-monkey/blob/389464ec39cf2fe7472ac45d9aa6d869acbfcd47/Framework/Model/Setup_Loader.php#L176
そうすると `app/customizer` の読み込みが、連結された1つのファイルの読み込みになります。とりあえず手っ取り早く試したいのであれば、カスタマイザー > ページ読み込み速度最適化 > 設定ファイルの読み込み方式 を `concat` でもできます（これをすると  `app/customizer` だけではなくて `app/setup` なども同じよう連結された1つのファイルの読み込みになります）。

**Comment by inc2734** [comment]
@waviaei 

> concat が見つかりません。実装されたverを教えてください。

ディレクトリということですかね？ ディレクトリがないときは、適当なページにアクセスがあったとき（`Setup_Loader::load()` が `concat` で呼ばれたとき）に自動的に生成されるようになっています。
https://github.com/inc2734/snow-monkey/blob/389464ec39cf2fe7472ac45d9aa6d869acbfcd47/Framework/Model/Setup_Loader.php#L52-L71

**Comment by waviaei** [comment]
@inc2734 すみません、そういうことではなく、 `snow-monkey/Framework/Model/Setup_Loader.php` のファイル自体がなく、カスタマイザー > ページ読み込み速度最適化 に「設定ファイルの読み込み方式」もありません。テーマのversionが14.3.2なのですが、14.x.x にはない機能なのかなと。

**Comment by inc2734** [comment]
@waviaei あ、なるほどです。15.4.0 からみたいです。
https://snow-monkey.2inc.org/2021/08/25/snow-monkey-v15-4-0/
