### ISSUE TITLE
編集画面にてテンプレートを現在設定してるものと別のもの選択するとリアルタイムで切り替わらない

### ISSUE THREAD

**Issue by kutsu123** [inc2734/snow-monkey#1315]
お疲れ様です。
ふと操作してて気づいたのですが、編集画面の設定パネル（投稿・固定ページ）で、テンプレートを切り替えようとすると、リアルタイムでは切り替わらないことに気づきました。

- テンプレートを既存の設定のものと別のものを選択し、フォーカスを外すと選択したテンプレートに切り替わっていない
- 一旦更新を行い、再度編集画面をリロードすると、選択したテンプレートに切り替わってるが、設定画面の表記は「デフォルトテンプレート」のまま？

https://user-images.githubusercontent.com/15826102/219827678-f2ddd075-8459-4719-bd09-08f7ba4c7cda.mp4

他のテーマだとリアルタイムで切り替わってるので（twenty-twenty-threeやSWELLなど）、テーマ側でなにかの指定を調整したらうまく動くかもしれないです（←私そのへんの仕組み全然わかってなく言ってて的外れだったらごめんなさい）

===

この現象はSnow Monkey v18の時点で起きてるようでした（検証できてるのがv18・v19の２つだけで情報少なくてすみません）

**Comment by inc2734** [comment]
あーほんとですね…。ちゃんと検証していないので本当のところはまだわからないのですが、SWELL だと Tempate name が日本語になっているのに対し、Snow Monkey は英語を翻訳しているのでそこが怪しい気がします。

TT3 も英語を翻訳ですが、unitone も英語を翻訳している形でちゃんと動くので、ブロックテーマ（あるいは theme.json でページテンプレートを指定？）だと英語を翻訳という形でも大丈夫なのかもしれません。時間あるときにちゃんと見てみます！

**Comment by inc2734** [comment]
メモ：

- 翻訳は関係なさそう
- `theme.json` があるとダメ
- `theme.json` があると `select( editPostStore ).getEditedPostTemplate()` が `undefined` になる

**Comment by inc2734** [comment]
@kutsu123 Gutenberg の不具合のようでした…。
https://github.com/WordPress/gutenberg/issues/47428

**Comment by kutsu123** [comment]
@inc2734 
お疲れ様です。ご確認・調査などありがとうございます！！
そしてお手数をおかけしてしまってすみません、Gutenberg側チェックするの全然頭になかったです、ごめんなさい。
シェアしてくれたIssue内容承知しました（トリアージされて修正されるといいなあ）

**Comment by inc2734** [comment]
ですねー。とりあえずここはクローズしておきます！
