### ISSUE TITLE
フル幅以外のテンプレートのフロントページ（固定ページ）にて全幅のブロックが全幅にならない

### ISSUE THREAD

**Issue by kutsu123** [inc2734/snow-monkey#1318]
@inc2734 
お疲れ様です。いつもありがとうございます。
さて、スリム幅（#1313）の対応の影響か、全幅に設定したブロック（例えばセクションブロック）のWidthが左右余白を加味した幅に設定されてしまっており、全幅で表示されなくなってしまってました。

https://demo.rui-jin-en.com/r002-lp-a/#flow
（このページはテンプレートを1カラムにしています）

**Comment by kutsu123** [comment]
すみません。こちら通常の固定ページだと大丈夫で、フロントページを固定ページにして、その固定ページが1カラムだと起きてるようです。（検証不足のままIssue立てやコメすみません）

**Comment by inc2734** [comment]
多分これで大丈夫だと思います！

**Comment by kutsu123** [comment]
@inc2734 
ご対応ありがとうございます。最新コミットで試してみたところ、全幅ブロック全幅になりました！
ありがとうございます
