### ISSUE TITLE
WooCommerceの商品詳細ページにて、冒頭の商品概要部分の幅がコンテンツ幅より大きくなってしまってる

### ISSUE THREAD

**Issue by kutsu123** [inc2734/snow-monkey#1320]
@inc2734 
お疲れ様です。
Snow Monkey本来の使い方の範疇をちょびっと超えてしまった部分になりますが、WooCommerce上で表示が意図しないものになってしまってるところを発見したのでお知らせします。

対象：
- 商品詳細ページ（product-single?）
- 使用テンプレートは1カラム
- 冒頭に挿入される商品概要（商品のギャラリーと商品情報が入った部分）の２カラムのコンポーネントの幅がコンテンツ幅を超えてしまってる（余白を加味したフル幅表示になってしまってる）

例：
https://shop.m-g-n.me/product/rje-r002lp/

---

こちら、そもそも出力されたHTML自体がやっかいで、2カラムの親のdivがいない（コンポーネントのwrapperがない）ので、Snow Monkey側でどうにかなるのかっていう感じもしてて・・・。

一旦報告だけ上げましたが、Snow Monkey側では無理！でIssue閉じてももちろん構いません。

**Comment by inc2734** [comment]
うおーーほんとですね、全然気づいていませんでした…。

本当は `woocommerce/templates/content-single-product.php` を上書きしたほうが良いのでしょうが、メンテナンスを考えるとちょっと微妙なところなので、summary の前後のフック `woocommerce_before_single_product_summary` と `woocommerce_after_single_product_summary` で `<div>` と `</div>` を出力するようにしてみようと思います！
ご報告ありがとうございます！

**Comment by kutsu123** [comment]
@inc2734 
ご返答ご対応ありがとうございました！！ フックでdiv入るのとても助かります。（Snow Monkeyとは違う領域のことまで対応していただいてありがとうございます）
