### ISSUE TITLE
PHP8.1環境下で「XSERVER 登録キー登録」登録画面でエラーがでる

### ISSUE THREAD

**Issue by kutsu123** [inc2734/snow-monkey#1360]
お疲れ様です。
エラーがでた箇所があったのでお知らせします（PHP8.1の環境なので、対応外だったらすみません。8.0だとエラーはでません）

## 現象が起きる画面
設定 > Snow Monkey の「XSERVER 登録キー登録」の入力フィールド

![スクリーンショット 2023-06-16 19 14 13](https://github.com/inc2734/snow-monkey/assets/15826102/3973a89d-6de9-4a75-bdfa-5fd685516426)

**Comment by inc2734** [comment]
あ、変数名が間違ってました。ご報告ありがとうございます！
