### ISSUE TITLE
ランキングと任意の投稿ウィジットでタイトルのない投稿が表示される場合がある

### ISSUE THREAD

**Issue by munyagu** [inc2734/snow-monkey#14]
ランキングと任意の投稿ウィジットで投稿を選択するリストがありますが、そこにタイトルのない投稿が表示され、そのアイテムの高さが低くなっています。

通常の投稿でタイトルがないものは表示されないのですが、Gutenbergで作成した投稿はタイトルがなくても表示されてしまいます。

通常はこのような条件は起こりえないから問題ないのか不具合なのか判断がつきませんでしたが、報告させていただきました。
![any-ranking](https://user-images.githubusercontent.com/19759754/31490931-8e73d4c4-af80-11e7-87b9-cd3fb48ed7ac.png)

**Comment by inc2734** [comment]
ご報告ありがとうございます。WordPress のテーマユニットテストデータで空タイトル時にそのような挙動になることは把握しておりますが、実害がないと判断しそのままにしていましたw
タイトルが空のときは`&nbsp;`を入れるような処理を追加するのが良いかなと考えています。
