### ISSUE TITLE
一覧ページのスマホ用レイアウトが、２カラムから１カラム表示に変わっている

### ISSUE THREAD

**Issue by rokuzeudon** [inc2734/snow-monkey#140]
v1.1.0にアップデート後、もともと２列表示だった一覧ページが１カラムになっているようです。

![2018-03-06 12 08 17](https://user-images.githubusercontent.com/14285777/37012271-4923c6c6-2137-11e8-98e9-2633f9528e57.jpg)

（機能変更のアナウンスがあったようであれば、見落としておりすみません…）

**Comment by inc2734** [comment]
あ！すみません。。
2カラムだと、幅の問題でインフィード広告がエラーを吐くためにそうしていたのですが、インフォームド広告未設定の場合は2カラムにしようと思っていたのを反映するのを忘れていました…。次のアップデートでその修正を入れてみます。

**Comment by rokuzeudon** [comment]
おお、そういうことでしたか！ぜひお願いします〜☺️
