### ISSUE TITLE
snow-monkey.zipファイルがダウンロードできない

### ISSUE THREAD

**Issue by bagel-saki** [inc2734/snow-monkey#1416]
【お使いのブラウザ】Chrome

### 発生している問題

先ほどテーマの購入をしましたが、snow-monkey.zipファイルのみダウンロードできません。

ダウンロードボタンをクリックしてもダウンロードが開始されず、

（管理者により削除）

こちらに遷移して止まってしまいます。

その他のファイル、my-snow-monkey.zip、snow-monkey-google-fonts.zip、snow-monkey-diet.zip

は通常通りダウンロードできています。

### 試したこと

メール添付のダウンロードリンクからのダウンロード

再ログイン

ダウンロードできず作業が進めることができず困っています。

よろしくお願いいたします。

**Comment by inc2734** [comment]
サポートフォーラムのほうで進めたいと思いますので、こちらクローズします。
https://snow-monkey.2inc.org/forums/topic/snow-monkey-zip%e3%81%8c%e3%83%80%e3%82%a6%e3%83%b3%e3%83%ad%e3%83%bc%e3%83%89%e3%81%a7%e3%81%8d%e3%81%aa%e3%81%84/
