### ISSUE TITLE
one-column-slim のときはパンくずもスリム幅にする

### ISSUE THREAD

**Issue by inc2734** [inc2734/snow-monkey#142]

**Comment by rokuzeudon** [comment]
たまたま見かけたのでコメントさせていただきます、
ヘッダーレイアウトが横並び（シンプルor１列）の時はパンくずスリム幅にならないようになってると嬉しいです！

ロゴとパンくずの位置が揃ってる方が見栄えが良いので…！

**Comment by rokuzeudon** [comment]
あ、でもそう思うかどうかは人によるか…( ˘ω˘ ）

**Comment by inc2734** [comment]
なるほど！Snow Monkey のサイトが中央揃えになってて、それでみたときに変だなと感じたので issue たてたのですが、確かにロゴが左にあるときはそのほうが良い気がします。やるとしたら中央揃えのときだけ、にしようかなと思いますが、となると HTML の構造もちょっと見直さないといけないかもなので、ちょっとどうするか検討します。ご指摘ありがとうございます！

**Comment by inc2734** [comment]
あ、そうか、ページヘッダーも関係しますね。僕もページヘッダーないページでみてたので忘れてました^^;
頂いたアドバイスをもとにどういう形が良いかもう一回整理して、やるかどうかも含め検討してみます。
