### ISSUE TITLE
ライセンス認証が通りません。数に制限はありますか？

### ISSUE THREAD

**Issue by minamixmx** [inc2734/snow-monkey#1426]
ライセンス認証が通りません。数に制限はありますか？

**Comment by inc2734** [comment]
下記と同じでしょうか？
https://snow-monkey.2inc.org/forums/topic/%e3%83%a9%e3%82%a4%e3%82%bb%e3%83%b3%e3%82%b9%e8%aa%8d%e8%a8%bc%e3%81%8c%e9%80%9a%e3%82%8a%e3%81%be%e3%81%9b%e3%82%93%e3%80%82%e6%95%b0%e3%81%ab%e5%88%b6%e9%99%90%e3%81%af%e3%81%82%e3%82%8a%e3%81%be/
