### ISSUE TITLE
Toolset TypesプラグインのPotsType追加画面でエラー

### ISSUE THREAD

**Issue by munyagu** [inc2734/snow-monkey#15]
[Toolset Typesプラグイン](https://ja.wordpress.org/plugins/types/)のPostType追加画面で、以下のエラーが表示されます。

Notice: Trying to get property of non-object in /data/webmst/test.barbwire.jp/wp-content/themes/snow-monkey/vendor/inc2734/wp-seo/src/app/controller/seo.php on line 28

add_meta_boxesフィルタに空の$post_typeを投げているToolset Typesが悪いのかもしれませんが・・・

**Comment by inc2734** [comment]
あ、いえ、これは僕の判定がわるいですね。ご指摘ありがとうございます！
【メモ】コード参照 https://github.com/inc2734/wp-seo/blob/master/src/app/controller/seo.php
