### ISSUE TITLE
IE11 で flex コンテナに flex-direction: colunm; 指定時に flex アイテムの高さが無視される

### ISSUE THREAD

**Issue by shodoi** [inc2734/snow-monkey#158]
![ie11-flex-direction-bug](https://user-images.githubusercontent.com/759562/38047260-ef5f0b00-32fc-11e8-9fde-fba8f0c703ec.png)

・参考
[【WEB】【備忘録】flex-direction:column　IE10/11で高さが認識されない | 追憶の夜想曲](http://novel.neziko-web.net/web/2015-09-18/)

**Comment by inc2734** [comment]
ぎゃー！IE…
お知らせありがとうございます！
