### ISSUE TITLE
ソーシャルナビの Behance 対応

### ISSUE THREAD

**Issue by inc2734** [inc2734/snow-monkey#182]
https://snow-monkey.2inc.org/forums/topic/%E3%82%BD%E3%83%BC%E3%82%B7%E3%83%A3%E3%83%AB%E3%83%8A%E3%83%93%E3%82%B2%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%81%AE%E3%82%A2%E3%82%A4%E3%82%B3%E3%83%B3%E5%A4%89%E6%9B%B4%E6%96%B9%E6%B3%95/

**Comment by rokuzeudon** [comment]
ついでと言っては恐縮ですが、この辺りも追加いただけるとありがたいです
（私の観測範囲内だと使ってる方が少なからずいらっしゃるので…）

https://fontawesome.com/icons/500px?style=brands
https://fontawesome.com/icons/blogger?style=brands
https://fontawesome.com/icons/soundcloud?style=brands
https://fontawesome.com/icons/spotify?style=brands
https://fontawesome.com/icons/foursquare?style=brands

**Comment by inc2734** [comment]
対応します！
