### ISSUE TITLE
グローバルナビゲーションをタブで操作すると3階層目を閉じることができない

### ISSUE THREAD

**Issue by masuP9** [inc2734/snow-monkey#186]
https://snow-monkey.2inc.org/ でいうと `マニュアル > WordPressの詳細設定 > WP Multibyte Patch プラグインの有効化` がタブキー操作で閉じることができない。

![header_menu_tab_operation_demo](https://user-images.githubusercontent.com/6724665/39456740-c0b81170-4d23-11e8-875a-b5cc0c83bd3b.gif)

おそらく `focus` で開いて `blur` で閉じてないような（該当の箇所のコード見つけられませんでした…）

**Comment by inc2734** [comment]
ご報告ありがとうございます！この辺知識が乏しく対応するのが遅くなってしまいました。修正入れて、多分改善されたはずです…！ひとまずクローズします。

**Comment by masuP9** [comment]
ご対応、ありがとうございます！https://snow-monkey.2inc.org/ で3階層目閉じられてるの確認しました！

対応 commit https://github.com/inc2734/snow-monkey/commit/66d8b89ca0362e328fb42c3ddb104b4a119ece2a 見てみたのですが、JSっぽいファイルがなくて。この辺のコードって snow-monky のコードとしては管理されてないんでしょうか？

**Comment by inc2734** [comment]
あ、そうですね。Snow Monkey はベースに Basis という CSS フレームワークとして を使っているのですが、グローバルナビゲーションはそのコンポーネントを使っています。Basis は、

Mimizuku Core（composer）→ WP Basis（Composer）→ Basis（npm）という経由で使っていて、Snow Monkey 側ではコード管理していないんです。

Basis での当該コミットはこれですね！
https://github.com/sass-basis/basis/commit/b9482f4b213d0a4fdb68b4bad7a06c2d52049210
