### ISSUE TITLE
Kusanagi 環境でアップデートに失敗する

### ISSUE THREAD

**Issue by inc2734** [inc2734/snow-monkey#21]
という報告あり。

**Comment by hinaloe** [comment]
草薙だとセキュリティ上の対策とか称してファイルオーナーがPHPの実行と異なるためと思われ。（FTP要求されるやつ）

**Comment by inc2734** [comment]
僕も多分それが原因かなとは思っています。でも FTP 入力してもアップデートできなかったと報告を受けれいるので、別の要因もからんでいるのかもしれません。

ひとまず権限関係でアップデートできないときは、ダッシュボードにアラートを出して手動で FTP なりで更新してくださいと促すようにしようかなぁと。
