### ISSUE TITLE
ループをカスタマイズできるようにしてほしい

### ISSUE THREAD

**Issue by fumikito** [inc2734/snow-monkey#255]
https://github.com/inc2734/snow-monkey/blob/d160ba91dfb50cf76cea69fc8a4fc0a5aa459029/resources/templates/view/archive-post.php#L33

上記のリンクのような場所なんですが、よくあるワークアラウンドとしてはこんな感じにしています。

```
get_template_parts( 'template-parts/loop', get_post_type() );
```

この場合、book という投稿タイプがあり、なおかつ子テーマで`template-parts/loop-book`というファイルを用意（多くはloop.phpのコピペ）しておけば自動で読み込まれ、他の投稿タイプに関してはなければ元の`template-parts/loop.php`が使われます。

今回、ジョブボードを作成しているのですが、アーカイブ全体の構造自体は特にいじる必要性を感じていないものの、ループの見栄えだけ変えたいという要望があるので、ぜひ実装をお願いします。

**Comment by inc2734** [comment]
あーなるほどです。僕は投稿タイプによって `view/archive-book.php` みたいにつくる想定でいましたが、これだと切り出し方が大きいわけですね。

`<?php get_template_part( 'template-parts/entry-summary', get_post_type() ); ?>`

となっていれば良さそうでしょうか？

**Comment by inc2734** [comment]
下記の issue とも絡んできますね。
https://github.com/inc2734/snow-monkey/issues/256

<?php get_template_part( 'template-parts/loop/entry-summary', get_post_type() ); ?>

として、

- template-parts/loop/entry-summary.php
- template-parts/loop/entry-summary-post.php

を用意しておくようにしようと思います（命名がちょっとしっくりきませんが…）。
