### ISSUE TITLE
カテゴリーがない場合にエラーが出ないようにする

### ISSUE THREAD

**Issue by fumikito** [inc2734/snow-monkey#256]
https://github.com/inc2734/snow-monkey/blob/d160ba91dfb50cf76cea69fc8a4fc0a5aa459029/resources/template-parts/entry-summary.php#L9-L21

投稿タイプによってはカテゴリーがないので、エラーになります。

> Notice: Trying to get property of non-object in /opt/local/www/capitalp.jp/wp-content/themes/snow-monkey/template-parts/entry-summary.php on line 21

```
if ( ! is_wp_error( $terms ) ) {
	$term  = $terms[0];
}
```

ではなく、

```
$term = null;
if ( $terms && ! is_wp_error( $terms ) ) {
	$term  = $terms[0];
}
```

とした上で、`term->term_id` をやめるといいと思います。

```
c-entry-summary c-entry-summary--category-<?php echo $term ? esc_attr( $term->term_id ) '0'; ?>
```

**Comment by inc2734** [comment]
わ、そうか！ありがとうございます、修正します！
