### ISSUE TITLE
アップデートがコケたときにフォールバック

### ISSUE THREAD

**Issue by inc2734** [inc2734/snow-monkey#35]
エックスサーバーのような通常のレンタルサーバーでもアップデートにコケて「snow-monkey-K9fuSU」のようなテーマが残って再有効化できなくなることがある。コケたときはアップデートさせないみたいなことができないか。

**Comment by inc2734** [comment]
一応、コケたときはアップデートさせない（通知はでるけどファイルは置き換わらない）ようにしたつもりだけどどうだろう…

**Comment by masahico** [comment]
> 一応、コケたときはアップデートさせない（通知はでるけどファイルは置き換わらない）

このためなのか、0.7.0のアップデート通知が出てきません。
0.6.1にも気づいてなかったのでこの時からかもしれません。当方の環境は現在0.6.0です。
その前の2回は通知が出てアップデートできましたが、本issueのためフォルダ名が変わり手動で変更しました。

**Comment by inc2734** [comment]
コメントありがとうございます。
通知表示部分には特に手を加えていないので、「通知はでてアップデートボタンは押せるけど、押してもテーマは更新されないし、通知が出続ける」が正しい動作のはずなのです…。
WordPress はアップデートの確認を一定時間キャッシュするので、ちょっとその時間がどれくらいかはわからないのですが、例えばダッシュボードで更新チェックをしてそのときになければ、その間に最新版がでても半日は更新がでないとか、そういうことはありえます。

**Comment by masahico** [comment]
> 通知表示部分には特に手を加えていないので、「通知はでてアップデートボタンは押せるけど、押してもテーマは更新されないし、通知が出続ける」が正しい動作のはずなのです…。

更新確認してみましたけど通知は更新画面、テーマ画面ともに出ないですね。プラグインの更新通知は出るのですが。
このテーマのためか分からないのですが検索順位がガクンと下がったため、検証目的で一時的に以前のテーマに戻しているのですが、違うテーマを使っていると通知が出ないとかはありますか？

試しにSnow Monkeyに戻してみましたが通知は出ませんでした。
(で、テーマを戻したらウィジェットの配置がバラバラに。こちらももう一度やってみて再現したらご報告します)

**Comment by inc2734** [comment]
> 違うテーマを使っていると通知が出ないとかはありますか？

あ！そうでした、それをマニュアルに書くのを忘れていました。Snow Monkey 自体がアップデートに関するコードを持っているため、有効化されないと実行されないのでした。

> テーマを戻したらウィジェットの配置がバラバラに。

この問題は WordPress 4.9 から改善されるそうです。

> 検索順位がガクンと下がったため

むしろこの部分のほうが非常に問題ですね。。。

**Comment by masahico** [comment]
了解です。有効化させてみて試してみます。
ウィジェットの件はWordPressの問題なのですね。


以下は場所を変えた方が良いかもしれませんが。
検索順位の件はGoogleのことなのでテーマのせいではないのかもしれないのですが、タイミングがぴったり合うのでテーマを戻してしばらく様子見してます。
認識できているのは旧テーマは更新日付だけを載せていたので検索結果でもその日付が表示されますが、テーマを変えてからその記事の検索結果での日付が公開日に戻ったのが気になりました。3年以上前ですがちょくちょく更新している記事なので。
