### ISSUE TITLE
Fatal error caused by case-sensitive file paths

### ISSUE THREAD

**Issue by roborourke** [inc2734/snow-monkey#369]
I got a fatal error, _I think_ as a result of case-sensitive file names. It'll work on Windows servers at least.

```
PHP Fatal error: Uncaught Error: Call to undefined function Inc2734\Mimizuku_Core\App\Model\wpvc_config() in /srv/www/public/content/themes/snow-monkey/vendor/inc2734/mimizuku-core/src/App/Model/PageTemplates.php
```

The actual file path I have in the theme downloaded from the release is `/srv/www/public/content/themes/snow-monkey/vendor/inc2734/mimizuku-core/src/app/Model/PageTemplates.php`.

The `app` bit is lowercase in the release zip.

**Comment by inc2734** [comment]
What your Snow Monkey version ?

I downloaded v4.4.8, directory name is `App`. 

<img width="598" alt="2018-11-09 9 04 17" src="https://user-images.githubusercontent.com/1094306/48234800-76da0c80-e3fe-11e8-9f28-b4d708f7242f.png">

In the past version, it was `app`.

**Comment by roborourke** [comment]
@inc2734 it's 4.4.7, I'll try 4.4.8 - thanks!

**Comment by roborourke** [comment]
Ah ok, so that was corrected in 4.4.8 but I now have this error: 

```
PHP Fatal error: Uncaught Error: Call to undefined function Inc2734\Mimizuku_Core\App\Model\wpvc_config() in /srv/www/public/content/themes/snow-monkey/vendor/inc2734/mimizuku-core/src/App/Model/PageTemplates.php
```

Looks like a missing `use` statement.

**Comment by roborourke** [comment]
Ok, not sure what's going on here! I think there is some strange behaviour on my production server with composer.

**Comment by roborourke** [comment]
it looks like in some situations it's possible that `wpcv_config()` is called in the `PageTemplates.php` file before the `View_Controller()` class is referenced anywhere. Because that class file is responsible for loading the file with the `wpcv_config()` function it doesn't get loaded and causes a fatal error.

**Comment by inc2734** [comment]
Certainly, since `PageTemplates.php` expects `wpcv_config()` to be called first, I feel that design is not good.


I'd like to load `wpcv_config()` in the constructor of `Inc2734\Mimizuku_Core\Core()`.

**Comment by inc2734** [comment]
https://github.com/inc2734/mimizuku-core/blob/master/src/Core.php#L18

I can not reproduce the error, so I do not know if I could fix it, but how about this?
