### ISSUE TITLE
npm ERR! 404 Not Found: flatmap-stream@0.1.1

### ISSUE THREAD

**Issue by ryoraspp** [inc2734/snow-monkey#392]
npm install をしたところ、

npm ERR! 404 Not Found: flatmap-stream@0.1.1

というエラーが出ます。

npm install event-stream をすることで解決できそうです。

**Comment by inc2734** [comment]
ご報告ありがとうございます。npm-run-all が flatmap-stream@0.1.1 を使ってるのでアップデートしないとですね。
