### ISSUE TITLE
0.7.0 アップデート以降、SNSのカウントが全て0になった

### ISSUE THREAD

**Issue by mihoji** [inc2734/snow-monkey#44]
0.7.0 アップデート以降、SNSのカウントが全て0になり、その後も増えないようです。何か原因がわかりますでしょうか？
https://ishida-webkontor.com/2050/

**Comment by inc2734** [comment]
ぐわーすみません！
子テーマをお使いの場合に不具合がありました。
適当な js ファイルを用意して（空ファイルで結構です）、functions.php に下記のようなコードを追加して用意した js ファイルを読み込んでみてください。これでどうでしょう？

```
add_action( 'wp_enqueue_scripts', function() {
  wp_enqueue_script( get_stylesheet(), '適当な js ファイルのパス', [], false, true );
});
```

現在アップデート版を開発中ですので、それに修正を組み込みます。

**Comment by inc2734** [comment]
【メモ】
https://github.com/inc2734/wp-share-buttons/blob/master/src/app/abstract/cors.php#L39
が原因。
https://wpdocs.osdn.jp/%E9%96%A2%E6%95%B0%E3%83%AA%E3%83%95%E3%82%A1%E3%83%AC%E3%83%B3%E3%82%B9/wp_script_is
を使って `get_template()` もしくは `get_stylesheet()` ハンドルが存在するかをチェックし、それにバインドさせるようにする
