### ISSUE TITLE
トップページが oEmbed 埋め込みに変換されない

### ISSUE THREAD

**Issue by inc2734** [inc2734/snow-monkey#489]
https://snow-monkey.2inc.org/startup-guide/embed/
はいける

https://snow-monkey.2inc.org/embed
はだめ

**Comment by inc2734** [comment]
Snow Monkey だけじゃなくて他のテーマでも発生する気がする

**Comment by inc2734** [comment]
`apply_filters( 'post_embed_url', $embed_url, $post )`

**Comment by kmix-39** [comment]
?embedを使えばどうです？

https://snow-monkey.2inc.org/?embed=true

**Comment by inc2734** [comment]
まだちゃんとコード読めてなかったのですが、前述の `post_embed_url` で書き換えちゃえばいいんですかね？というよりこれ Snow Monkey というよりコアの問題な気がしますが…^^;

**Comment by kmix-39** [comment]
Snow Monkey外のテーマでも発生しますし、これは完全にコア側の問題です…w
コアもちょっとずつ調べてたんですが、パーマリンク設定によっても微妙に処理が変わってるようで完全に追えず。更にその問題がコア側なら、どうしろって状態だったんで、こっち側で書き換えちゃうしか…ないんじゃないですか。パーマリンクとかカスタム投稿設定とか色々変えてみましたが、すべてトップだけ取れず。
逆に?embedはすべて取れる…（謎
リダイレクトするように仕様変えられたとしか思えませぬ。（それがバグなのかは判別できず…

> 前述の post_embed_url で書き換えちゃえばいいんですかね？

多分、クエリに足して書き換えるようにするなどで出来ると思います。

**Comment by inc2734** [comment]
やっぱりコアですよねぇ…w ほんとはコアにチケット立てたほうが良いのでしょうが、よくわかってないのでやりにくい…。とりあえず Snow Monkey だけでも対応しようかなぁ（優先度低）。
