### ISSUE TITLE
ロゴが設定されていたら、ログイン画面のロゴもそれにしたい

### ISSUE THREAD

**Issue by inc2734** [inc2734/snow-monkey#491]
https://www.nxworld.net/wordpress/wp-custom-login-logo-url-title.html

**Comment by kmix-39** [comment]
https://wordpress.org/plugins/login-customizer/

ログイン画面のカスタマイズプラグインもあるので、どうでしょう
こう言ったプラグインで差し替えられている場合もあるので、ややこしいかも

**Comment by inc2734** [comment]
そうですね、issue たてたままなかなかやる気がでずそのままになってますし、一旦クローズします。
