### ISSUE TITLE
iPhoneでみるとサムネイルが正常に表示されない

### ISSUE THREAD

**Issue by mihoji** [inc2734/snow-monkey#5]
![img_3385](https://user-images.githubusercontent.com/12166608/31305290-3866386e-ab71-11e7-81ff-9649f61a58a1.PNG)
iPhone実機で確認しますと、個別記事のサムネイルがうまく表示されていません。

**Comment by mihoji** [comment]
![img_3391](https://user-images.githubusercontent.com/12166608/31370666-8d825cbc-adc7-11e7-9174-0834fc0a3eb9.PNG)
前回のアップデート後、だいじょうぶになりました！

**Comment by inc2734** [comment]
ご確認ありがとうございます！
