### ISSUE TITLE
iPadでみるとサムネイル画像がくずれている

### ISSUE THREAD

**Issue by mihoji** [inc2734/snow-monkey#51]
iPadでブログみたひとから教えてもらったんですが、サムネイル画像がちょっと変になるみたいです
![23828522_1527606000655587_2101374187_o](https://user-images.githubusercontent.com/12166608/32997674-54e22480-cdd6-11e7-9a3a-432866a59b80.jpg)

**Comment by mihoji** [comment]
![23768600_1527610193988501_1851909374_o](https://user-images.githubusercontent.com/12166608/32997688-8cc99cde-cdd6-11e7-9a4c-5755fbe82b2b.jpg)
縦にすると直るようです

**Comment by inc2734** [comment]
ご報告ありがとうございます！多分 `background-attachment: fixed` が問題ですね、これスマホだと不具合多いので…。メディアクエリで制御してたので、横の iPad だと効いちゃうみたいですね。ちょっと別の実装方法を考えます！
