### ISSUE TITLE
metaアイテムの表示整理

### ISSUE THREAD

**Issue by kmix-39** [inc2734/snow-monkey#534]
.c-meta__item+.c-meta__itemで
padding-leftに対して.75emを取っているが、
meta項目が増えた際に、２行目の右端がずれてしまっている。

`.c-meta__item:not(:last-child) {
padding-right: .75em;
}`

等で、最終のアイテムの左端以外に加えて先頭統一させるのは、どうでしょう？

また、長い項目を追加した場合、項目内の文章がスマホ等で折り返されず、画面から漏れている？（iPhoneで確認）

**Comment by inc2734** [comment]
あ！ほんとですね。left じゃなくて right のほうが良いですね。

`white-space: nowrap;` にしちゃってるので折返しの問題はありそう。https://github.com/inc2734/snow-monkey/issues/366 の問題を修正したものっぽいのですが、これって先日ケミさんが目次のやつで報告してくれてたやつと同じですかねー。ちょっと明日 nowrap 外して再確認してみます。

**Comment by kmix-39** [comment]
> white-space: nowrap; にしちゃってるので折返しの問題

nowrapにしてるから、折り返さなくなってしまったんだと思います。
画面に収まらない多めの文字を１項目にすると、画面外へはみ出しちゃうようです。
（スマホだと、ぐぐぐっと指でバウンス操作させて、無理やり画面外のを出せば見えるので多分はみ出してる…）

通常のmetaアイテムではみ出すとすれば、投稿者の名前くらいかも（それでも名前に２５文字以上は必要）
おそらく大丈夫な気はしますが、「この記事は約XXX分XX秒で読むことができます」とか「この記事の難易度はXXXXです」とかの良くあるニュース系の記事説明を入れるようなカスタムをすると、かなりはみ出す確率が高くなるようです。


目次のやつは、良く解らない所で改行が起きる問題なので、多分別な感じがします。

**Comment by kmix-39** [comment]
nowrapを外すと変な所で折り返しますね。（今、試しました）
なので、

```
.c-meta__item{
display:inline
}
```

を、 inline-block; にすれば、それを解決できるようです。
もしかしたら…それで対策が可能かも。
