### ISSUE TITLE
関数を削除する場合、deprecatedの期間をもうける

### ISSUE THREAD

**Issue by fumikito** [inc2734/snow-monkey#538]
`snow_monkey_get_page_title_from_breadcrumbs` 関数を使っていたのですが、アップデートしたら真っ白になりました。どこかのタイミングで削除されたのだと思います。

https://github.com/inc2734/snow-monkey/commit/5b8ccd8126a80fb1ec2d26335ab54ac5b9733216

`@deprected` タグをつけつつ、warning出すようにしてもらうと助かります。

**Comment by inc2734** [comment]
わーすみません！なるべく気をつけているつもりだったのですが、しばらく前にごそっと消してしまったことがあったみたいです。ちょっとこれまでどれどれを消したかがよくわからないので、次回分から対処するようにしようと思います。

ちなみにですが、Warning をだすのは `trigger_error` を使うのが一般的でしょうか？ 
https://www.php.net/manual/ja/function.trigger-error.php

**Comment by fumikito** [comment]
@inc2734 WordPressのコアは `_deprecated_function` という関数を廃止予定の関数の内部で実行していて、それが `trigger_error` してます。

```
trigger_error( $message, E_USER_WARNING );
```

ワーニングなら普通のレンサバではなにも表示されないけど、ローカル環境を用意して開発するような人（＝アンドキュメンテッドな関数を勝手に利用する僕みたいな人）は気づくことができます。

なので、普通に `_deprecated_function` を使ったらいいと思います。こんな感じ。

```
function start_wp() {
	global $wp_query;

	_deprecated_function( __FUNCTION__, '1.5.0', __('new WordPress Loop') );

	// Since the old style loop is being used, advance the query iterator here.
	$wp_query->next_post();

	setup_postdata( get_post() );
}
```

実装自体はそのままとっておくけど、警告が出るようになる。関数を消してしまうと、Fatal Errorになってしまうし、PhpStormなどを使っていれば、開発者はその関数がもう使えないことがすぐにわかる（関数呼び出しに打ち消し線がつく）。

って感じでしょうか。

**Comment by inc2734** [comment]
情報ありがとうございます！

> PhpStormなどを使っていれば、開発者はその関数がもう使えないことがすぐにわかる（関数呼び出しに打ち消し線がつく）

そんな機能もあるんですね、すごい。

`@deprecated` でマークしているものが現状でも何個かあるので、そこに `_deprecated_function` を入れようと思います。

あ、あと `snow_monkey_get_page_title_from_breadcrumbs()` を消してしまったのは多分 v4 から v5 になるときだったと思うのですが、近々またメジャーアップデートである v6 をリリースします。v5 にするときは後方互換性的にアレなことを結構やってしまったので今回は気をつけているつもりですが、カスタマイズ内容によっては影響が出るかもしれません。5.7.6 にして件の現象が起きたのであれば、ついでにもう v6 にあげちゃって、テストしたほうが良いかもしれません……。

https://snow-monkey.2inc.org/2019/05/23/snow-monkey-v6-rc/
