### ISSUE TITLE
hierarchy で追加したルートでページテンプレートの上書きができない

### ISSUE THREAD

**Issue by inc2734** [inc2734/snow-monkey#548]
https://github.com/inc2734/wp-view-controller/blob/master/src/setup/template-loader.php#L69-L71 はなくても良さそう。

↑が必要ないなら https://github.com/inc2734/wp-view-controller/blob/master/src/setup/template-loader.php#L109-L112 もいらない気がする。

ページテンプレート以外の通常ファイルは上書きできるかどうか確認する。
↑ template-parts は上書きされる。クエリテンプレートはダメ。

**Comment by kmix-39** [comment]
確かにL69-71は不要な気がします。
こちらでも検証出来る事あれば返信で言ってください。

結構typeもあるので、こちらでも思いついた検証は色々合間合間の時間取って行ってみます。

ページテンプレートってちょっとややこしくて、完全な上書きをして良いのかはあるので、条件判定を作らないと駄目な気もしますね。

パターンとして、
同一のファイル名で、片方はpost, pageのみ書かれたファイルで、片方がnewsと言うタイプだけを許可していた場合、どう上書きさせるかは少し問題な気がしますね。そのまま上書きして良いのか…それともタイプ別に違うファイルを使わせるのか。
元々の許可タイプも完全に上書き出来るかも、ちょっと調べてみる必要がありそうです？

**Comment by inc2734** [comment]
子テーマの場合は普通にそのまままるっと上書きなので、それにあわせるほうが良いと思います。「子テーマでできることをプラグインでもできるようにする」が目的なので。Template Post Type の拡張が何らかのフックでできるのかは調べてみたほうが良さそうですね。

**Comment by inc2734** [comment]
あ、というか編集画面でのカスタムテンプレート選択セレクトボックスってここ ( https://github.com/inc2734/wp-view-controller/blob/master/src/setup/custom-page-template-selector.php ) でカスタマイズしているので、ここにフックしこめばいいのかも…です

**Comment by kmix-39** [comment]
なるほど。子テーマの仕様に合わせるのカタチで納得です。

…そこかーい！w
あれ？選択セレクトボックスって無い時に強制的に出せましたっけ？

**Comment by inc2734** [comment]
いま試したらいけました！
