### ISSUE TITLE
テンプレート階層を変更した場合は警告を出す

### ISSUE THREAD

**Issue by fumikito** [inc2734/snow-monkey#556]
これまで何度かあったのですが、

- テンプレート階層が変更になる e.g. template-parts/google-adsense.php -> template-parts/common/google-adsense.php
- 子テーマを利用している場合、特にエラーは起きない。ただ単にそれが表示されなくなる。
- 特定のパーツが表示されなくなっていることに気づかない

ということが起きます。アップデートするときはなにも考えずにアップデートしたい（子テーマに変更を施すべきか判断したくない）ので、もしテンプレート階層が変わって、なおかつ子テーマに古いテンプレートが存在している場合は何らかの方法で警告を出してもらえると助かります。

WooCommerceの場合、[テンプレートが古いと警告が出る](https://capitalp.jp/2019/01/28/how-to-fix-woocommerce-template/)のですが、そんな感じをイメージしています。検討よろしくお願いします。

**Comment by inc2734** [comment]
僕がいうのもなんですが本当そうですよね…--;
当初想定していたよりテンプレートの数が増えてきて煩雑になってきたので v5 で階層を変更したんですよね。それ以降は階層の変更（追加はありましたが）はしていないと思いますが、次回から警告がだせるようになんらか仕組みを考えようと思います。

> もしテンプレート階層が変わって、なおかつ子テーマに古いテンプレートが存在している場合は何らかの方法で警告

例えば Snow Monkey で `template-parts/google-adsense.php` -> `template-parts/common/google-adsense.php` となったあとに、上書きしようという意図じゃなくて自分オリジナルのテンプレートを追加しようとして子テーマに `template-parts/google-adsense.php` を置いちゃう人もいると思うんですよね。そういうことで、前回指摘いただいた古い関数の対応は `_deprecated_function()` を使って画面上にもメッセージがでるようにしましたが、テンプレート階層の変更についてはログにだけだすようにしようと思います。

> WooCommerceの場合、テンプレートが古いと警告が出るのですが、そんな感じをイメージしています。検討よろしくお願いします。

各テンプレートにバージョンを持たせておいて、ということですよね。ちょっと面倒でやっていなかったのですが、そろそろそういうのもやったほうが良い時期かもしれませんね…。Woo みたいにダッシュボード上にだすかどうかは置いておいて、ログにはだせるようにしたいです。ちょっと Woo がどうやっているか見てみます。
