### ISSUE TITLE
`hamburger-btn` がスクリーンリーダー / キーボードで操作できない

### ISSUE THREAD

**Issue by masuP9** [inc2734/snow-monkey#6]
## 該当箇所

https://github.com/inc2734/snow-monkey/blob/702349ebf1b97b62e9fc579cba3df016cb08126f/resources/template-parts/hamburger-btn.php#L8-L12

## 原因

- `<div id="hamburger-btn">` がキーボードフォーカスを受け取れない
-  `<div id="hamburger-btn">` の内部にマシンーリーダブルなテキストが無いため、スクリーンリーダーのフォーカスも受け取れない（単なる空要素に見える） & フォーカスを受け取っても何を操作するものかがわからない

## 現象

Android TalkBack （Android 標準スクリーンリーダー）での操作動画
https://photos.app.goo.gl/5ZfHUYTBxDQjtsaJ2

## 対応方法の提案

[メニューボタンを span だけで実装するのは良くないのでやめた話](http://blog.rokuzeudon.com/entry/button_accessibility)

**Comment by inc2734** [comment]
おお、詳しくありがとうございます！ますぴーさんっぽい！
