### ISSUE TITLE
While I view on the iPhone, c-hamburger-btn__bar is not good.

### ISSUE THREAD

**Issue by ryoraspp** [inc2734/snow-monkey#609]
I'm sorry, but I want you to fix c-hamburger-btn__bar.

**Comment by ryoraspp** [comment]
![ss 2019-08-11 23 30 55](https://user-images.githubusercontent.com/30954577/62835195-3dd20f80-bc90-11e9-9193-2ba89c1e4b5e.jpg)

**Comment by inc2734** [comment]
カスタマイザー > デザイン > 基本デザイン設定
にあるロゴの拡大率で調整してみると改善しないでしょうか？

**Comment by ryoraspp** [comment]
AWESOME!
Oh,you are gosh!

**Comment by ryoraspp** [comment]
solved.! Thank you so much!
