### ISSUE TITLE
アドアド感をどうにかする

### ISSUE THREAD

**Issue by kmix-39** [inc2734/snow-monkey#655]
<img width="981" alt="スクリーンショット 2019-11-01 19 54 52" src="https://user-images.githubusercontent.com/34811629/68020369-96d6a000-fce1-11e9-8ef5-6b728ef0e954.png">

何かしらのGoogle広告ウィジェットを入れるとヘッダーがアドアド感全開になる。

**Comment by kmix-39** [comment]
CSSのdisplay: noneとかで消すのはGoogleアドセンス的に宜しくないっぽいので、
display: noneでアドアド感を見えなくするんじゃなくて、何かしらHTMLごとアドアド感の存在そのものを抹消した方がいいっぽい。
その方がキャピキャピする！！

**Comment by kmix-39** [comment]
Google側の問題もあるって事なんで、とりあえずCSSで見えなくしておく。
困ってる人も多いと思うんで お知らせでスタイルを周知。

**Comment by kmix-39** [comment]
公式も結構被害受けている…
何かしらのテコ入れはいるかも。。

<img width="1147" alt="スクリーンショット 2019-11-06 10 36 27" src="https://user-images.githubusercontent.com/34811629/68260805-6c8a3700-0081-11ea-9c48-870cd7a457f0.png">

**Comment by inc2734** [comment]
あれーまじですか…。なぜかぼくの環境では自動広告がでなくて気付きませんでした。

自動広告オフってるんですけどねー。どうしましょ…

<img width="900" alt="スクリーンショット 2019-11-06 10 41 37" src="https://user-images.githubusercontent.com/1094306/68261026-2681a300-0082-11ea-9a52-6192c6969d56.png">

**Comment by kmix-39** [comment]
うちも、オフってます……が出ます。
お知らせで共有しているCSSを入れて自動広告を出さない（断定対応）でも良い気がします…。

後は、フッターのカラム毎の下に表示される時があって、その時はフッターのデザインが壊滅しています。
（客の環境でそうなったらしくて、急遽CSSで対策取りました…）

入る位置とかサイトによって違うっぽいし、これは確かに対策なんてできないなーと。
困った

**Comment by inc2734** [comment]
うーんサブドメインだからですかねー、いずれにバグっぽい挙動ですけど。CSS で消すとなにかあったときに「CSS で消してるから BAN された」「CSS で消してるから収益下げられた」という人がでてくると思うので、Snow Monkey 側でどうこうというのはやりたくないんですよね…。本来アドセンスサイトでオフっとけばでないはずなので、やりたい人が自分でやるくらいにしておきたいんです。

ただ、「カスタマイザー > 広告」「広告ウィジェト」の設定は全体的に見直したほうが良さそうですね。もう自動広告用の入力欄とかいらないんでしょうし。

**Comment by kmix-39** [comment]
Google側でadの自動挿入位置の対策がされたのか、Snow Monkeyであっても現状はだいぶマシになっている（っぽい）。
一部、変な位置に入ったりもまだ多少する場合もあるが、自動広告オフにすれば問題は起こらない。
（基本的にカラムブロックやセッションブロックで適当に組むと広告が入って崩れるっぽい）

最新の Snow Monkey では 自動広告オフ にすれば、正しく自動広告も入らなくなっているので、
とりあえず自動広告オフにすれば問題がなくなると言うことで。クローズしておきます。


> ただ、「カスタマイザー > 広告」「広告ウィジェト」の設定は全体的に見直したほうが良さそう

この辺りって、もう見直されていたっけ…？（汗

**Comment by inc2734** [comment]
> 最新の Snow Monkey では 自動広告オフ にすれば、正しく自動広告も入らなくなっているので、
> とりあえず自動広告オフにすれば問題がなくなると言うことで。クローズしておきます。

なにもせず解決できて良かったです笑

> この辺りって、もう見直されていたっけ…？（汗

特に見直したりはしていませんが、先日スマホでの表示はちょっと変えました。

https://github.com/inc2734/snow-monkey/issues/839
