### ISSUE TITLE
キーボード操作時の挙動

### ISSUE THREAD

**Issue by shodoi** [inc2734/snow-monkey#66]
- Tab キーによるフォーカス移動の際にグローバルナビゲーションが重複して選択されます。（ファーストビューで表示されるものとスクロール時に固定で表示されるもの）
一方が表示されている際に他方に display: none; 付与で解決しそう。
- サブメニューを持つメニューにフォーカスが当たった際、サブメニューが表示されない。
デフォルトテーマの場合 navigation.js がフォーカスが当たったメニューに .focus を付与して CSS で良しなにしている様子。

**Comment by inc2734** [comment]
ありがとうございます！
