### ISSUE TITLE
オーバーレイ時にトグルメニューの真ん中のバーが白で出る

### ISSUE THREAD

**Issue by kmix-39** [inc2734/snow-monkey#674]
オーバーレイ時にトグルメニューの真ん中のバーが白で出るので

`.c-hamburger-btn[aria-expanded=true]>.c-hamburger-btn__bars>.c-hamburger-btn__bar:nth-of-type(2) {
background-color: transparent;
}`

上記のスタイルは

`.l-header[data-l-header-type=overlay][data-snow-monkey-header-position-fixed=false] .c-hamburger-btn__bar, .l-header[data-l-header-type=overlay][data-snow-monkey-scrolling-header-colored=false] .c-hamburger-btn__bar, [data-scrolled=false] .l-header[data-l-header-type=overlay][data-snow-monkey-header-position-fixed=true] .c-hamburger-btn__bar {
background-color: #fff;
}`

で上書きされてしまうので、

`.c-hamburger-btn__bar:not(:nth-of-type(2)) {`

と、not要素を追加する。

同時に普通の状態で真ん中のバーが出なくなるので
`.c-hamburger-btn[aria-expanded=false]>.c-hamburger-btn__bars>.c-hamburger-btn__bar:nth-of-type(2) {
background-color: #fff;
}`
を追加する。

SCSSの該当部分が何処か解らんのでとりあえず直し方だけ共有

**Comment by inc2734** [comment]
あ！ほんとですね。報告ありがとうございます！発生条件は

- オーバーレイ
- 開いたとき
- スクロールしていないとき

ですかね。ちょっと見てみます。
