### ISSUE TITLE
カスタマイザーの「レイアウト」と「デザイン」を統合したい

### ISSUE THREAD

**Issue by inc2734** [inc2734/snow-monkey#682]
### v8.3.1 現在

<img width="914" alt="スクリーンショット 2019-12-10 11 24 19" src="https://user-images.githubusercontent.com/1094306/70489623-a8f8f900-1b3f-11ea-9a58-79d6429fe600.png">

**Comment by yamasakidaisuke** [comment]
ざーっと見ただけでも作業量も多いし、難しい。大変そう＞＜
ありがとうございます！！
