### ISSUE TITLE
グローバルナビのサブメニューについて

### ISSUE THREAD

**Issue by baccccck** [inc2734/snow-monkey#724]
### 問題①：
グローバルナビのサブメニューが220pxで固定されておりサブメニューの文字が意図しない位置で改行されてしまう

- CSSで`.c-navbar__submenu`の`position`に`left`と`right`が指定されているため可変になっていない
- `min-width:220px`が指定されていることから本来は可変を想定しているのでは？

### 提案①：
- `.c-navbar__submenu`に`right:auto`を指定する
- `.c-navbar__subitem > a`に`white-space:nowrap`を指定する

文字の改行位置に関しては、改行タグを入れることでユーザー側で調整が可能になります
（最小幅は220pxのまま上記CSSで可変にした場合）

### 問題②：
上記と関係なく、1行ヘッダーにした場合サブメニューが画面外に出ることがある
#### 画面外に出る条件：
- ブラウザサイズが1280px程で親メニューの文字数が少ない場合
- サブメニューが2階層目・3階層目と階層が深い場合

### 提案②：
- 1行ヘッダーの場合だけ右側に出ているサブメニューを左側に出す
（例：`left:50%`を`left:auto;right:0`に変更する）
※その場合▲の位置がサブメニューに依存するため親メニューの位置に変更する等が必要
- 1行ヘッダーの場合だけ2階層目・3階層目は表示しない等

**Comment by inc2734** [comment]
> min-width:220pxが指定されていることから本来は可変を想定しているのでは？

確かに CSS の指定が不可解ですね^^;  `white-space: nowrap` は後方互換の影響が大きそうなのが気になるところですが、現状のまま行くよりはそのほうが良いのかなぁというところですね…うーん。

> 上記と関係なく、1行ヘッダーにした場合サブメニューが画面外に出ることがある

これは対処に悩みますね…。1行じゃない場合でも、メニューの文字列や階層によってはみでる場合があると思います。本当は開く都度はみだすかどうか条件判定してはみだす場合は左にだす、のようにできれば良いと思うのですが、submenu の長さが可変だとその判定も難しそうだなという気がします。ここは下手に対処するよりユーザーにメニューの構成を工夫してもらうのが良いかなぁと思います。

**Comment by inc2734** [comment]
> submenu の長さが可変だとその判定も難しそうだなという気がします。

や、そんなことないか、現状展開のたびに場所を計算しているわけではなくて、CSS で静的に位置がきまった状態で消す/表示するを切り替えているだけなので、CSS で静的に位置決定 → 画面からはみででているときは逆方向に JS で展開しなおしを繰り返せばいいのかな…ちょっとテストしてみます。

**Comment by inc2734** [comment]
試してみました。開くたびに条件判定して右 or 左に開くことは技術的には可能。ただ、3階層以降のメニューを左に開く場合はその前階層のメニューにかぶる形で開くことになるわけだけど、同時に変更をおこなっている「メニュー幅の可変」の影響で、「長いメニュー項目に短いメニュー項目がかぶる」という状態になり、非常に見た目がわるくなる場合があります。

なので、都度判定よりは、一番深い階層のメニューが画面右端にかかる場合は、最初のメニューからして左に展開する、としたほうが良さそう。その場合、階層がめっちゃ深い場合は今度は画面左端にかかっちゃうという問題がでてくるけど、それはそんなに深く階層を掘らないで…とするしかなさそう。
