### ISSUE TITLE
文字色や背景色を選択したと時に適用されない場合がある

### ISSUE THREAD

**Issue by baccccck** [inc2734/snow-monkey#746]
主に見出しのH2で文字の色や背景の色を変更したい場合
色が適用される場合と適用されない場合がある
（管理画面では適用されていますが、表示画面では適用されていない）

これは優先度の関係でsnow monkeyで書き出される
`has-xxx-color`や`has-xxx-background-color`だと適用されていないみたいです

`wp-includes/css/dist/block-library/style.min.css`で書き出されている色のcssは適用されます
そちらは`:root .has-xxx-～`なので優先度の関係で適用されているようです

例）
has-luminous-vivid-amber-color（オレンジ選択）⇒文字色変わる
has-accent-color-color（アクセントカラー選択）⇒文字色変わらない

snow monkeyの書き出しにも:rootを付与して欲しいです
よろしくお願いします😭

**Comment by inc2734** [comment]
ご報告ありがとうございます！色設定したときはもう絶対にその色にしたいときだと思いますので、`!important` にしようと思います。`:root` つけても詳細度競争で変わらないところがでてくると複雑になっていくので…。もし問題がでたらまた考えます。
