### ISSUE TITLE
mod_expiresモジュール未対応のサーバーで「ブラウザキャッシュを使用する」をONにすると500エラーになる

### ISSUE THREAD

**Issue by ko31** [inc2734/snow-monkey#765]
レンタルサーバー [GMOクラウド iCLUSTA](https://shared.gmocloud.com/) 上で Snow Monkey を使用している環境にて、

- 外観 > カスタマイズ > ページ速度最適化 > 「ブラウザキャッシュを使用する」を ON に更新

という操作をした時に、500 Internal Server Error が発生する状況に出くわしました。

「ブラウザキャッシュを使用する」を有効にすると .htaccess に下記の設定が追記されますが、
iCLUSTA は mod_expire モジュールに未対応という仕様のため、エラーが起きてしまったようです。
（ファイルの該当行を手動削除することでエラーは解消しました。）

```
<ifModule mod_expires.c>
ExpiresActive On
<FilesMatch "\.(css|js)$">
ExpiresDefault "access plus 1 weeks"
Header set Cache-Control "max-age=1209600, public"
</FilesMatch>
<FilesMatch "\.(gif|jpg|jpeg|png|svg|ico|bmp)$">
ExpiresDefault "access plus 1 weeks"
Header set Cache-Control "max-age=1209600, public"
</FilesMatch>
<FilesMatch "\.(ttf|otf|woff|eot)$">
ExpiresDefault "access plus 1 weeks"
Header set Cache-Control "max-age=1209600, public"
</FilesMatch>
</IfModule>
```

参考までに、何かエラー回避する方法はないものかな…とちょっと調べてみましたが、
動作環境が Apache モジュール版の PHP に限っては、
`apache_get_modules` や `phpinfo` 関数からモジュールが有効かどうかを判別して処理することはできそうですが、
CGI 版 PHP ではその手法は使えず、どの環境においても汎用的に対応するのは難しそうに見えました。

ただこれは iCLUSTA 以外のレンタルサーバーでも起きうる問題かな？と思いましたので、
もし可能でしたら以下のような対応を行っておくのはいかがでしょうか。

- マニュアルや FAQ ページなどに注意書きを記載しておく。
- カスタマイザーの設定箇所の辺りに注意書きを記載しておく。

もし、どこかで既出の内容でしたらすみません！ご報告までに。

**Comment by inc2734** [comment]
なるほど！ありがとうございます！ `IfModule` で囲っててもダメなんですね…。判別は難しそうなので、カスタマイザーに説明を記載するようにしようと思います。

**Comment by ko31** [comment]
htaccess に記述できるディレクティブにも制限がある仕様のようなので、
`IfModule` も効かない環境なのかもしれません。
（すみません、サポートに訪ねても下記ページが回答される程度ではっきりしたことはよく分かりませんで…。）
https://helpcenter.gmocloud.com/iclusta/s/article/ch-524
