### ISSUE TITLE
snow_monkey_append_drawer_navの位置がズレている気がします

### ISSUE THREAD

**Issue by miminari** [inc2734/snow-monkey#795]
https://github.com/inc2734/snow-monkey/blob/4db2c53e6ab9f31510e1c55d94b100884390e6f6/resources/template-parts/nav/drawer.php#L52

なのですが、 `c-drawer__inner` のdivタグ内に入っている必要があるのでは、と思ったのですが、いかがでしょうか？現状だとちょっとCSS頑張らないといけない気がしているのですが、勘違いだったらごめんなさい！

**Comment by inc2734** [comment]
確かに！変更入れます！
