### ISSUE TITLE
Readme.mdの修正

### ISSUE THREAD

**Issue by kmix-39** [inc2734/snow-monkey#842]
RequirementsをWordPress 5.5とする場合、
WP5.5以降のみ対応のv11リリース時に再度修正するのがタイミングとして良いかも。

現状…下記の部分も見直してみてください。

+ Browser supportは、IE10+はサポート範囲なのか微妙に怪しい。

+ Third-party resourcesでは、
`wp-adsense`
`wp-google-fonts`

などが抜けている。

**Comment by inc2734** [comment]
ご指摘ありがとうございます！まったくメンテしませんでした^^;
メンテがめんどくさいので、自分のものは Third-party resources から外しました！
