### ISSUE TITLE
ソーシャルナビゲーションの対応サービスの追加

### ISSUE THREAD

**Issue by kmix-39** [inc2734/snow-monkey#856]
忘れないようにメモ

https://snow-monkey.2inc.org/forums/topic/ソーシャルナビゲーションに『line』『note』を対応さ/

より。

note（ https://note.com/ ）
LINE（ https://lin.ee/ ）

---

また、下記のアイコンも公式SNS的な使われ方をするケースもあるので、
ソーシャルナビゲーションとしては追加対応も考えたい。（必要かどうかは要判断）

アプリ配信系サイト
app store( https://apps.apple.com )
google play store( https://play.google.com )
開発会社のアプリページにリンクを貼る使い方をする場合がある

ゲーム配信・ゲームニュース系サイト
twitch( https://www.twitch.tv/ )
discord（ https://discord.com 招待URLは https://discord.gg )
「配信を見逃すな！」的にYoutubeアイコンと並べて使われているケース

音楽配信系サイト
apple music (アイコンはitunes https://music.apple.com )
アーティストのページをソーシャルとして紹介するケースがある

エンジニア系
Qiita (アイコンが無いので、SVGを自前で生成しないといけなさそう）

FontAwesomeにないアイコンを、どう生成するか、アイコンに当てるスタイルやクラス仕様を決めるのも必要か…。

**Comment by inc2734** [comment]
FontAwesome にあるものは優先的に、SVG があるものは必要に応じて追加しようと思います！

**Comment by kmix-39** [comment]
FontAwesome以外のSVGの方は、どのようにクラス名とか作るかの仕様決まれば、こちらでも対応できるので、また仕様など決まったりすれば言うて下さい。

軽量化FA作る際に同じようにiタグをSVGにするjsにオリジナルアイコン含める形で作る方が楽ですかねー…うーむ
