### ISSUE TITLE
WooCommerceの商品サムネイルを拡大した際、ヘッダーが被る

### ISSUE THREAD

**Issue by kmix-39** [inc2734/snow-monkey#888]
商品サムネイルを虫眼鏡ボタンなどで拡大した際にヘッダーが覆いかぶさる（中央ロゴで確認済み）

商品画像が小さい場合などはヘッダーに重ならないが、大きいサイズであれば縮小された画像はヘッダーに重なるので途切れて見えてしまう。
また、右上のバツボタンなどがヘッダーに重なる為正しく表示されていない。

**原因：**

ヘッダーの方が .pswp(woocommerceのサムネイル画像クラス）より z-index が高い為に起こる。

**対策：**

```
.pswp {
	z-index: 99999;
}
```

などでヘッダーよりz-indexを高くすれば対策可能。

**Comment by inc2734** [comment]
気づいてませんでした、ありがとうございます！

これ、ヘッダーの z-index が高すぎる気もするので、ヘッダーの方を下げようと思います！

**Comment by kmix-39** [comment]
`.pswp`はデフォルト1500だったはずです（Wooの更新が来てるので変わった可能性はあり）

確かにヘッダーのz-index高すぎる…かも。
とは言え、下げる場合は念のため数値を更新される際のアップデート情報に記載していただければー。

1000くらいが良いのかもですねー。
ヘッダーカスタマイズの影響はz-indexだと起こらないと思うけど、下げ過ぎは禁物だし…。
海外のブロックでz-index使ってるのもちらほら見かけるので。大きいのはz-index:100とか500とかも。個人的に1000辺りが安心な感じしてます。

**Comment by inc2734** [comment]
ちょうどいま 1000 で push したところでしたw 9999 → 1000 ですね。
