### ISSUE TITLE
テーマをアップデートしたら子テーマが消えた

### ISSUE THREAD

**Issue by mihoji** [inc2734/snow-monkey#9]
今朝、テーマのアップデートをしたら子テーマ「snow-monkey-child」が消えてしまいました。
テーマフォルダの中に、もともとの「snow-monkey」と「snow-monkey-adJsu3」みたいな、旧親テーマと新親テーマだけ残っているかんじです。

そして、テーマディレクトリ名が変わったため、ウィジェットの位置がリセットされてしまいました。

**Comment by inc2734** [comment]
ご報告ありあがとうございます。調査します。

**Comment by inc2734** [comment]
【メモ】親テーマである Snow Monkey にではなく、子テーマを GitHub 上の Snow Monkey で上書きしようとしてしまう不具合が原因。「ダッシュボード > 更新」の画面で、テーマの更新対象が Snow Monkey ではなく子テーマになっている場合はアップデートしないこと。

**Comment by inc2734** [comment]
@mihoji ご迷惑おかけして大変申し訳ございません。アップデート及び報告＆対処法のお知らせを書きましたのでご参照頂ければと思います。
https://snow-monkey.2inc.org/2017/10/09/v0-3-6-%E4%BB%A5%E4%B8%8B%E3%81%A7%E3%81%AE%E5%AD%90%E3%83%86%E3%83%BC%E3%83%9E%E5%88%A9%E7%94%A8%E6%99%82%E3%81%AE%E3%82%A2%E3%83%83%E3%83%97%E3%83%87%E3%83%BC%E3%83%88%E3%81%AB%E9%96%A2%E3%81%99/

**Comment by mihoji** [comment]
ありがとうございます！確認しましたー。
