### ISSUE TITLE
ヘッダー画像、ショーケースサムネイルの画質設定

### ISSUE THREAD

**Issue by inc2734** [inc2734/snow-monkey#95]
今は大サイズ固定なので、フルサイズも選べたほうが良いかも。もしくはフック。検討。

**Comment by ykawato** [comment]
合わせて、カスタム投稿タイプのsingleにもヘッダー画像を表示するために、snow_monkey_is_output_page_header() にもfilterがあると嬉しいです。

**Comment by inc2734** [comment]
@ykawato なるほどですね。`snow_monkey_is_output_page_header ` だけじゃなくて、`snow_monkey_is_output_page_header_title()` にもあったほうが良さそうかなと思いました。アドバイスありがとうございます！
