### ISSUE TITLE
ストレージが遅い場合、functions.php の Helper::get_template_parts() がボトルネックになります。

### ISSUE THREAD

**Issue by wokamoto** [inc2734/snow-monkey#958]
https://github.com/inc2734/snow-monkey/blob/df71fdae76f01706e5aeb2243ff3813ea1d31121/functions.php#L71

遅いストレージ( 具体的にいうと Amazon EFS )を使用している場合 /app/customeizer 以下の php ファイルを全て get_template_parts() で読み込む処理がボトルネックになります。
以下のように require に変更することで、多少は改善しました。

```
/**
 * Loads customizer
 */
add_action(
	'init',
	function() {
		do_action( 'snow_monkey_pre_load_customizer' );
		foreach ( [ '/app/customizer' ] as $include ) {
			//Helper::get_template_parts( untrailingslashit( __DIR__ ) . $include );
			$iterator = new RecursiveDirectoryIterator( untrailingslashit( __DIR__ ) . $include );
			$iterator = new RecursiveIteratorIterator( $iterator );
			foreach ( $iterator as $file ) {
				if ( $file->isFile() && 'php' === $file->getExtension() ) {
					require $file->getPathname();
				}
			}
		}
		do_action( 'snow_monkey_post_load_customizer' );
	},
	10000
);
```

**Comment by inc2734** [comment]
情報ありがとうございます！`Helper::get_template_parts()` だといろんな関数やフックを経由する分遅くなってしまうのかもしれませんね…。

`get_template_part()` ではなく `include_once()` でファイルを読み込ませる `Helper::include_files()` というメソッドも用意しているのですが、`RecursiveDirectoryIterator` + `RecursiveIteratorIterator` のやり方を知らず独自に再帰処理をつくっていたので（`Helper::get_template_parts()` も同様）、`RecursiveDirectoryIterator` + `RecursiveIteratorIterator` のやり方に書き換えてみようと思います！

**Comment by wokamoto** [comment]
確認ありがとうございます。
include_files() は、こんな感じで再帰で include() できると思います！
参考にしていただくと幸いです。

``
function include_files( $directory, $exclude_underscore = false ){
	$directory = realpath( $directory );

	if ( ! is_dir( $directory ) ) {
		return;
	}

	$iterator = new RecursiveDirectoryIterator( $directory );
	$iterator = new RecursiveIteratorIterator( $iterator );
	foreach ( $iterator as $file ) {
			if ( $file->isFile() ) {
				if ( 'php' !== $file->getExtension() ) {
					continue;
				}
				if( $exclude_underscore && 0 === strpos( $file->getBasename(), '_' ) ) {
					continue;
				}
				include $file->getPathname();
			}
	}
};
```

**Comment by inc2734** [comment]
ありがとうございます、試してみます！！
